server:
 port: 1402
spring:
 application:
  name: shopapp
 datasource:
  url: jdbc:mysql://localhost:3306/shopapp #?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: # Nhập mật khẩu nếu cần
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: none
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQL8Dialect
     format_sql: true
 servlet:
  multipart:
   max-file-size: 10MB
   max-request-size: 10MB
api:
 prefix: api